### ISSUE TITLE
Command not support: "flutter:requestData" i cannot launch app using the Deeplink url with this command

### ISSUE THREAD

**Issue by vigneshwari1997** [appium-userland/appium-flutter-driver#195]
My Code:

await driver.execute('flutter:requestData', JSON.stringify({"deepLink": "https://altais.test-app.link/5yYsWgLgnkb"}))

My log:

COMMAND executeScript("flutter:requestData", <object>)
2021-10-21T11:01:59.148Z INFO webdriver: DATA {
  script: 'flutter:requestData',
  args: [ '{"deepLink":"https://altais.test-app.link/5yYsWgLgnkb"}' ]
}
2021-10-21T11:01:59.729Z WARN webdriver: Request failed with status 500 due to Appium error: An unknown server-side error occurred while processing the command. Original error: Command not support: "flutter:requestData"

Can anyone please help me on this how to launch the app using the deeplink URL?

**Comment by KazuCocoa** [comment]
The original error was by the flutter driver about _Command not support: "flutter:requestData"_. It was fixed by Appium 1.22.0.

The above was responded by the flutter VM https://github.com/flutter/flutter/blob/9421627324c27c5256e87fe3244a8867de9f338b/packages/flutter_driver/lib/src/common/handler_factory.dart#L211. It was not this driver stuff.

> [HTTP] --> POST /wd/hub/session/91362a5f-a885-49cc-b6f0-dbe0a08bf571/execute/sync
[HTTP] {"script":"flutter:requestData","args":["{"deepLink":"https://altais.test-app.link/5yYsWgLgnkb"}"]}
[W3C (91362a5f)] Calling AppiumDriver.execute() with args: ["flutter:requestData",["{"deepLink":"https://altais.test-app.link/5yYsWgLgnkb"}"],"91362a5f-a885-49cc-b6f0-dbe0a08bf571"]
[FlutterDriver] Executing Flutter driver command 'execute'
[W3C (91362a5f)] Responding to client with driver.execute() result: {"isError":false,"response":{"message":"No requestData Extension registered"},"type":"_extensionType","method":"ext.flutter.driver"}


Their official documentation addressed as:
> This enables generic communication between the driver and the application. It's expected that the application has registered a DataHandler callback in enableFlutterDriverExtension that can successfully handle these requests.

https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/requestData.html
https://api.flutter.dev/flutter/flutter_driver_extension/enableFlutterDriverExtension.html

Did you implement the DataHandler in your application code?
