### ISSUE TITLE
How to generate ios-sim-debug.zip 

### ISSUE THREAD

**Issue by WenhaoWu** [appium-userland/appium-flutter-driver#201]
Hello, maybe a stupid question, but how to generate the zip file for iOS simulator that can execute Appium test?

I tried listing all *.app files under ~/Library/Developer/Xcode, but not luck still. 

Thanks in advance.

**Comment by KazuCocoa** [comment]
What do you mean...? Do you mean `.app` file for a simulator?
For example, `.app` in `~/Library/Developer/Xcode/DerivedData/WebDriverAgent-bayyryijrpijfqgjdjnvsrngjuhe/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app` is it.
If you'd like to create a zip to put it in a web server so that appium server can download it and install it, simply you can compress the `WebDriverAgentRunner-Runner.app` as `WebDriverAgentRunner-Runner.app.zip` (for example).
Then, appium will unzip it after downloading it.

**Comment by WenhaoWu** [comment]
Hi thank you so much!
