### ISSUE TITLE
Do we really need to use appium flutter driver to test the apps using appium which are designed in flutter?

### ISSUE THREAD

**Issue by narasimhanukala** [appium-userland/appium-flutter-driver#231]
Do we really need to use appium flutter driver to test the apps using appium which are designed in flutter?

any help would be appreciated.

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/issues/229#issuecomment-1000101132

**Comment by KazuCocoa** [comment]
If you needed to access Dart VM to invoke https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html, then yes. This driver is necessary.
But for a release build, XCUITest driver can work. This driver does not work in the case.

**Comment by sanneabhilash** [comment]
@narasimhanukala, as per my experience, the switch context provided by appium-flutter has been useful in some cases but the limited interactions available with flutter elements make this a non-feasible solution.

Other issues we are facing:
- ValueKey locator is only available in the flutter context, Xpath is only available in the native context, flutter elements can't fetch all elements details
- Uniquely identifying controls is an issue using Xpaths, but if ValueKeys are used, they are not available using the inspector tools apart from flutter inspector, which needs DEV code access (might not be available to all team members)
- Even if control is identified using ValueKey, you cannot perform any common actions like getText, IsSelected, IsChecked, IsEnabled. Mostly click operations and setText works for us
- The fusion of appium-flutter, enabling us to switch context results in storing 2 locators for single control, one is ValueKey and another one is Xpath (for android). This is meaningless.

**Comment by narasimhanukala** [comment]
Thanks @sanneabhilash for providing the challenges being faced. 
it gives an impression that it is a challenging task using appium flutter driver.
otherwise, if we don't use appium flutter driver, then we need to maintain the two separate automation code base for ios and android though application is single, which is completely against the idea of flutter implementation i.e. single code base for both ios and android i believe.

**Comment by sanneabhilash** [comment]
In my point of view, the Flutter team should come up with a solution.
Appim-Flutter has its challenges derived from flutter_driver, and we can't proceed forward with it for full-scale automation.
Appium looks more suitable tool because I can't find a better alternative.

I do like the idea of flutter having a single code base, but imagine building a small 500 UI test cases regression (with good assertions) suite for an enterprise app developed using flutter completely. I don't see a working solution here other than having two codebases (or a single code base with lots of conditional switches for IOS/android)

**Comment by sanneabhilash** [comment]
> Thanks @sanneabhilash for providing the challenges being faced. it gives an impression that it is a challenging task using appium flutter driver. otherwise, if we don't use appium flutter driver, then we need to maintain the two separate automation code base for ios and android though application is single, which is completely against the idea of flutter implementation i.e. single code base for both ios and android i believe. any thoughts on this?

@narasimhanukala  In my point of view, the Flutter team should come up with a solution.
Appim-Flutter has its challenges derived from flutter_driver, and we can't proceed forward with it for full-scale automation.
Appium looks more suitable tool because I can't find a better alternative.

I do like the idea of flutter having a single code base, but imagine building a small 500 UI test cases regression (with good assertions) suite for an enterprise app developed using flutter completely. I don't see a working solution here other than having two codebases (or a single code base with lots of conditional switches for IOS/android)
