### ISSUE TITLE
Sometimes "find" methods (byValueKey, byTooltip and e.t.c.) don't work

### ISSUE THREAD

**Issue by ViktorPashkevich** [appium-userland/appium-flutter-driver#333]
I don't know the actual reason but sometimes I can't find an element using "find" methods. Notably, when I can find element by key, I can find it using other ways(byTooltip and others), from the other hand, if I can't - no find methods work. And I don't see any reason/criteria how to detect so called "non-findable" elements.

 I see the logging of my click but the action isn't performed and there is no INFO RESULT log.

![photo_5258350403936959934_y](https://user-images.githubusercontent.com/71842423/189665774-2a00b1e2-2496-434f-a6b1-f5c504208e21.jpg)

Please, make it a little bit more clear for me.
Maybe, you can provide some additional information about using keys in AppDialogs, Tappable widgets (especially, where I need to place key in the tree hierarchy) or some other development-required information. In my flutter app I declare keys as ValueKey("actualValue") and tooltips as Tooltip class with value inside (As described in example section).

**Comment by KazuCocoa** [comment]
appium-flutter-driver is just a proxy to send [flutter_driver](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) command to the DartVM and get the response in the Flutter context. So if an element exists depends on Flutter side. This driver itself does not have much error handling since the request by the flutter may change.

maybe what this driver could do is add links to Flutter documentation from https://github.com/appium-userland/appium-flutter-driver#usage
