### ISSUE TITLE
Any way to identify an Active element?

### ISSUE THREAD

**Issue by arctouch-felipeschiquetti** [appium-userland/appium-flutter-driver#371]
I would like to do something similar to:

1 - click on username field
2 - assert username is currently focused on

Is this possible? I tried driver.switch_to.active_element but it does not seem to work with flutter elements.

**Comment by KazuCocoa** [comment]
It could if https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html had since this flutter context depends on the library.
Or you may be able to do via NATIVE_APP context (then, via uia2 or xcuitest driver). If the element is exposed to the OS's accessibility features, it may work

**Comment by arctouch-felipeschiquetti** [comment]
Thank you @KazuCocoa, unfortunately trying to use Native also did not work, since the focused element displays focused="false" in the native page tree. Must be a custom Flutter implementation to show what is selected on screen. I will close this question.
