### ISSUE TITLE
appium/appium inspector hanging

### ISSUE THREAD

**Issue by bqMoonlight** [appium-userland/appium-flutter-driver#394]
Hi,
I am able to install and start the AUT but appium hangs and prints something like this every few seconds

`Calling appiumdriver.gettimeouts() with arg longidafter
Executing flutter driver command gettimeouts
Reaponding to client with
 driver.gettimeouts()

Timeouts 304 `

And this just keep being printed out, on appium inspector it just shows blank screen.

It works with uiautomator2.
The app follows all conditions required by the appim flutter driver

Regards

**Comment by ashwithpoojary98** [comment]
check below usage before run your app

Your Flutter app-under-test (AUT) must be compiled in debug or profile mode, because Flutter Driver does not support running in release mode.. Also, ensure that your Flutter AUT has enableFlutterDriverExtension() before runApp. Then, please make sure your app imported [flutter_driver](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) package as its devDependencies as well.

This snippet, taken from [example dir](https://github.com/appium-userland/appium-flutter-driver/tree/main/example), is a script written as an appium client with webdriverio, and assumes you have appium server (with appium-flutter-driver installed) running on the same host and default port (4723). For more info, see example's [README.md](https://github.com/truongsinh/appium-flutter-driver/tree/main/example/README.md)

**Comment by KazuCocoa** [comment]
Appium inspector does not work for this driver, especially flutter context because _Flutter context does not support page source_ https://github.com/appium-userland/appium-flutter-driver#note.

For Appium server, it may work with the latest one with proper configuration as ashwithpoojary98 addressed

**Comment by bqMoonlight** [comment]
Well the better question,if i cant see this with inspector, how can i get the field ids,paths etc?

Regards

**Comment by bqMoonlight** [comment]
I did i have appium 2 latest version (beta 48? And appium works properly, i
can install app and i can launch it.
What does not work properly is appium inspector, when i set capabilities
and start the app through appium inspector it works,untill it needs to load
screen and there its stuck.
Appium server then starts giving 304 response, and appium inspector has
white window with message gathering source infor or something like that,i
can add it later.

Starting app with uiautomator2 driver works with no issues
So i assume its either flutter driver or inspector.
My machine is macbook and my phone is samsung android.

Thanks

**Comment by ashwithpoojary98** [comment]
'automationName': 'Flutter'
 this capability will not support the inspector.

**Comment by bqMoonlight** [comment]
So basicly i use flutter in my code,but for the inspector i should use the
uiautomator2.
Right?

**Comment by ashwithpoojary98** [comment]
yes

**Comment by KazuCocoa** [comment]
Another note is `getRenderTree` will return the Flutter elements tree, but the format is string by Flutter. It won't work with the inspector https://github.com/appium-userland/appium-flutter-driver#note
