### ISSUE TITLE
Flutter: I've some problem on appium flutter driver 1.14.3

### ISSUE THREAD

**Issue by wanchai2540** [appium-userland/appium-flutter-driver#444]
Why can run Runner.app is find but .ipa isn't working? 

My Flutter project is build ipa mode profile. This app connected on iphone 11.

[
<img width="682" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/58947369/228769643-ac14a1d2-d6f4-44c8-b8e3-99437b845adc.png">
](url)

Can you help me?

appium-server(version): 2.0.0-beta.57
appium-flutter-driver (version): 1.14.3
Flutter(version): 3.7.3

**Comment by KazuCocoa** [comment]
Could you share the entire appium server log?

**Comment by ashwithpoojary98** [comment]
@wanchai2540 I hope Your Flutter app-under-test (AUT) must be compiled in debug or profile mode because Flutter Driver does not support running in release mode. Also, ensure that your Flutter AUT has enableFlutterDriverExtension() before running the app. Then, please make sure your app imported the [flutter_driver](https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html) package as its dependencies as well.

**Comment by KazuCocoa** [comment]
Yea, please try to add flutter_driver in the dependency. Let me add the dependency in the readme as well
